<html>
<?php
//This shows how easy it is to use the database access objects (DAO)
//DAO generated by the PHPDAO generator found from: http://phpdao.com/
require_once('include_dao.php');

//Get the player DAO (Database Access Object)
$playerDAO = DAOFactory::getPlayerDAO();
//Get the game DAO (Database Access Object)
$gameDAO = DAOFactory::getGameDAO();

//GET Player 1 FROM THE DATABASE AND DISPLAY
print_r($playerDAO->load("1"));   //Get and print out the details for player 1 using DAO model layer	
echo '<br/><br/>';                //Put a line break in the page

//GET ALL PLAYERS FROM THE DATABASE IN AN ARRAY AND DISPLAY
print_r($playerDAO->queryAll());  //Get and print out ALL players using DAO model layer	
echo '<br/><br/>'; 				  //Put a line break in the page


//GET ALL GAMES FROM THE DATABASE IN AN ARRAY AND DISPLAY
print_r($gameDAO->queryAll());    //Get and print all the game details using the DAO model layer
echo '<br/><br/>'; 				  //Put a line break in the page

//INSERT A PLAYER - WITH A null VALUE
$player = new Player;
$player->playerID = 5;
$player->playerName = null;
$player->playerPassword = 'Test33';
$playerDAO->insert($player);

echo'<br/><br/>'; //Put a line break in the page
print_r($player); //Print out the contents of the Player data object
echo'<br/><br/>'; //Put a line break in the page

//TEST QUERY BY NAME
print_r($playerDAO->queryByPlayerName('Edgy Ed'));


?>

</html>